name: movie_app
description: A cinematic movie browsing application using TMDB API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^16.3.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
